window.EmbyMusicConfig = {
  APP_NAME: "Emby Music Web",
  APP_VERSION: "0.92.83",
  DEFAULT_SERVER_URL: "",
  LOCK_SERVER_URL: false,
  ACCOUNT_PROFILES_KEY: "emby-music-web/account-profiles",
  SESSION_KEY: "emby-music-web/session",
  DEVICE_KEY: "emby-music-web/device-id",
  RECENT_KEY: "emby-music-web/recent-tracks",
  QUEUE_KEY: "emby-music-web/queue",
  LIBRARY_VIEW_KEY: "emby-music-web/library-view",
  FILTER_STATE_KEY: "emby-music-web/filter-state",
  SEARCH_HISTORY_KEY: "emby-music-web/search-history",
  PLAY_MODE_KEY: "emby-music-web/play-mode",
  SORT_KEY_KEY: "emby-music-web/sort-key",
  SORT_ORDER_KEY: "emby-music-web/sort-order",
  TRACK_DENSITY_KEY: "emby-music-web/track-density",
  PLAYER_META_TARGET_KEY: "emby-music-web/player-meta-target",
  PLAYBACK_STREAM_KEY: "emby-music-web/playback-stream-policy",
  TRANSCODE_BITRATE_KEY: "emby-music-web/transcode-bitrate",
  AUDIO_QUALITY_PROFILE_KEY: "emby-music-web/audio-quality-profile",
  VOLUME_KEY: "emby-music-web/volume",
  MAX_RECENT_TRACKS: 80,
  MAX_PERSISTED_QUEUE_TRACKS: 500,
  SERVER_SEARCH_DEBOUNCE_MS: 360,
  SERVER_SEARCH_LIMIT: 90,
  SERVER_SEARCH_MIN_LENGTH: 2,
  PLAY_MODES: ["order", "repeat-all", "repeat-one", "shuffle"],
  PLAYBACK_STREAM_POLICIES: ["auto", "direct", "transcode"],
  AUDIO_QUALITY_PROFILES: [
    {
      id: "direct-flac",
      label: "原始无损",
      codec: "FLAC DirectPlay",
      bitrate: 0,
      bitrateLabel: "原码率，1-6Mbps+",
      quality: "最高",
      stability: "最不稳",
      scene: "局域网、本地缓存、网络很好",
      mode: "direct",
      protocol: "direct",
      container: "",
      audioCodec: "",
      transferMethod: "direct",
      transferFormat: "FLAC 原文件",
      recommended: false,
    },
    {
      id: "hls-aac-384",
      label: "高音质",
      codec: "AAC",
      bitrate: 384000,
      bitrateLabel: "384kbps",
      quality: "很高",
      stability: "很稳",
      scene: "推荐默认高音质",
      mode: "universal",
      protocol: "hls",
      container: "ts",
      audioCodec: "aac",
      transferMethod: "hls",
      transferFormat: "AAC + HLS .ts 分片",
      recommended: true,
    },
    {
      id: "hls-aac-320",
      label: "高音质",
      codec: "AAC",
      bitrate: 320000,
      bitrateLabel: "320kbps",
      quality: "很高",
      stability: "很稳",
      scene: "移动网络/公网推荐",
      mode: "universal",
      protocol: "hls",
      container: "ts",
      audioCodec: "aac",
      transferMethod: "hls",
      transferFormat: "AAC + HLS .ts 分片",
      recommended: false,
    },
    {
      id: "http-aac-256",
      label: "平衡",
      codec: "AAC",
      bitrate: 256000,
      bitrateLabel: "256kbps",
      quality: "好",
      stability: "很稳",
      scene: "大多数手机听歌",
      mode: "universal",
      protocol: "http",
      container: "aac,m4a",
      audioCodec: "aac",
      transferMethod: "http",
      transferFormat: "AAC 单文件流",
      recommended: false,
    },
    {
      id: "http-aac-192",
      label: "普通",
      codec: "AAC",
      bitrate: 192000,
      bitrateLabel: "192kbps",
      quality: "一般偏好",
      stability: "非常稳",
      scene: "弱网",
      mode: "universal",
      protocol: "http",
      container: "aac,m4a",
      audioCodec: "aac",
      transferMethod: "http",
      transferFormat: "AAC 单文件流",
      recommended: false,
    },
    {
      id: "http-aac-128",
      label: "省流",
      codec: "AAC",
      bitrate: 128000,
      bitrateLabel: "128kbps",
      quality: "一般",
      stability: "最稳",
      scene: "流量敏感",
      mode: "universal",
      protocol: "http",
      container: "aac,m4a",
      audioCodec: "aac",
      transferMethod: "http",
      transferFormat: "AAC 单文件流",
      recommended: false,
    },
    {
      id: "http-opus-320",
      label: "高效高音质",
      codec: "Opus",
      bitrate: 320000,
      bitrateLabel: "320kbps",
      quality: "很高",
      stability: "稳",
      scene: "客户端支持 Opus 时",
      mode: "universal",
      protocol: "http",
      container: "webm,opus,ogg",
      audioCodec: "opus",
      transferMethod: "http",
      transferFormat: "Opus 单文件流",
      recommended: false,
    },
    {
      id: "http-opus-256",
      label: "高效高音质",
      codec: "Opus",
      bitrate: 256000,
      bitrateLabel: "256kbps",
      quality: "很高",
      stability: "稳",
      scene: "客户端支持 Opus 时",
      mode: "universal",
      protocol: "http",
      container: "webm,opus,ogg",
      audioCodec: "opus",
      transferMethod: "http",
      transferFormat: "Opus 单文件流",
      recommended: false,
    },
    {
      id: "http-mp3-320",
      label: "兼容兜底",
      codec: "MP3",
      bitrate: 320000,
      bitrateLabel: "320kbps",
      quality: "好",
      stability: "稳",
      scene: "老设备/浏览器兼容",
      mode: "universal",
      protocol: "http",
      container: "mp3",
      audioCodec: "mp3",
      transferMethod: "http",
      transferFormat: "MP3 单文件流",
      recommended: false,
    },
    {
      id: "remux-directstream",
      label: "Remux/DirectStream",
      codec: "换封装",
      bitrate: 0,
      bitrateLabel: "基本无损",
      quality: "基本无损",
      stability: "看客户端支持",
      scene: "不重编码，只换封装",
      mode: "universal",
      protocol: "http",
      container: "m4a,mp3,webm,flac,wav",
      audioCodec: "",
      transferMethod: "remux",
      transferFormat: "不重编码，只换封装",
      directStream: true,
      recommended: false,
    },
    {
      id: "pcm-wav",
      label: "PCM/WAV",
      codec: "PCM/WAV",
      bitrate: 1536000,
      bitrateLabel: "约 1.5Mbps+",
      quality: "接近无损",
      stability: "带宽更大",
      scene: "不推荐公网",
      mode: "universal",
      protocol: "http",
      container: "wav",
      audioCodec: "pcm_s16le",
      transferMethod: "pcm",
      transferFormat: "PCM/WAV",
      recommended: false,
    },
  ],
  SORT_KEYS: ["recent", "title", "artist", "album", "duration"],
  SORT_ORDERS: ["default", "asc", "desc"],
  TRACK_DENSITIES: ["comfortable", "compact"],
  PLAYER_META_TARGETS: ["immersive", "nowPlaying"],
  PLAY_MODE_LABELS: {
    order: "顺序",
    "repeat-all": "循环",
    "repeat-one": "单曲",
    shuffle: "随机",
  },
  PLAYBACK_STREAM_LABELS: {
    auto: "自动（直连优先）",
    direct: "仅直连",
    transcode: "优先转码",
  },
  PLAYER_META_TARGET_LABELS: {
    immersive: "沉浸播放页",
    nowPlaying: "原正在播放页",
  },
  TRANSCODE_BITRATES: [
    { value: 384000, label: "384 kbps" },
    { value: 320000, label: "320 kbps" },
    { value: 256000, label: "256 kbps" },
    { value: 192000, label: "192 kbps" },
    { value: 128000, label: "128 kbps" },
    { value: 96000, label: "96 kbps" },
  ],
  PAGE_SIZE: {
    albums: 84,
    tracks: 220,
    artists: 72,
    favorites: 120,
    playlists: 72,
  },
  itemFields: [
    "Album",
    "AlbumId",
    "AlbumArtist",
    "AlbumArtists",
    "ArtistItems",
    "Artists",
    "ChildCount",
    "DateCreated",
    "Genres",
    "ImageTags",
    "IndexNumber",
    "MediaSources",
    "MediaType",
    "ParentIndexNumber",
    "PlaylistItemId",
    "PrimaryImageAspectRatio",
    "ProductionYear",
    "RunTimeTicks",
    "SortName",
    "UserData",
  ].join(","),
};
